theme: jekyll-theme-cayman
title: Alejandro Escalante Mtz
show_downloads: true
other:
  home: https://alejandroescalantemtz.github.io/
  docs: https://alejandroescalantemtz.github.io/docs/document_index.html
  about: https://alejandroescalantemtz.github.io/pages/about.html
  test_url: https://www.youtube.com/watch?v=ucAyib45TP8&ab_channel=VictorHugo
  test_in_folder: AlejandroEscalanteMtz.github.io/folder/TESTINGIDK.md
