theme: jekyll-theme-cayman
title: Alejandro Escalante
description: una pagina personal
show_downloads: true
other:
  home: https://alex-esc.github.io/
  docs: https://alex-esc.github.io/docs/document_index.html
  about: https://alex-esc.github.io/pages/about.html
